### Develop a machine learning model to classify restaurants based on their cuisines.

In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [6]:
df=pd.read_csv("restaurant data.csv")
print(df.head(2))

   Restaurant ID   Restaurant Name  Country Code         City  \
0        6317637  Le Petit Souffle           162  Makati City   
1        6304287  Izakaya Kikufuji           162  Makati City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   

                     Cuisines  ...          Currency Has Table booking  \
0  French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   
1                    Japanese  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is d

In [8]:
df.drop('Restaurant ID', axis=1, inplace=True) 
df.drop('Country Code', axis=1, inplace=True) 
df.drop('City', axis=1, inplace=True) 
df.drop('Address', axis=1, inplace=True) 
df.drop('Locality', axis=1, inplace=True) 
df.drop('Locality Verbose', axis=1, inplace=True) 
df.drop('Longitude', axis=1, inplace=True) 
df.drop('Latitude', axis=1, inplace=True) 
df.drop('Currency', axis=1, inplace=True) 
df.drop('Has Table booking', axis=1, inplace=True) 
df.drop('Has Online delivery', axis=1, inplace=True) 
df.drop('Is delivering now', axis=1, inplace=True) 
df.drop('Switch to order menu', axis=1, inplace=True) 
df.drop('Price range', axis=1, inplace=True) 
df.drop('Aggregate rating', axis=1, inplace=True) 
df.drop('Rating color', axis=1, inplace=True) 
df.drop('Rating text', axis=1, inplace=True) 
df.drop('Votes', axis=1, inplace=True)

In [10]:
df

Restaurant Name                          Cuisines  \
0             Le Petit Souffle        French, Japanese, Desserts   
1             Izakaya Kikufuji                          Japanese   
2       Heat - Edsa Shangri-La  Seafood, Asian, Filipino, Indian   
3                         Ooma                   Japanese, Sushi   
4                  Sambo Kojin                  Japanese, Korean   
...                        ...                               ...   
9546               Naml? Gurme                           Turkish   
9547              Ceviz A??ac?   World Cuisine, Patisserie, Cafe   
9548                     Huqqa            Italian, World Cuisine   
9549               A???k Kahve                   Restaurant Cafe   
9550  Walter's Coffee Roastery                              Cafe   

      Average Cost for two  
0                     1100  
1                     1200  
2                     4000  
3                     1500  
4                     1500  
...                    ...  
9546                    80  
9547                   105  
9548                   170  
9549                   120  
9550                    55  

[9551 rows x 3 columns]

In [12]:
df.isnull().sum()

Restaurant Name         0
Cuisines                9
Average Cost for two    0
dtype: int64

In [14]:
df.dropna(inplace=True)

In [16]:
df.shape

(9542, 3)

In [18]:
missing_values = df.isna().sum() 
missing_values_column = df['Restaurant Name'].isna().sum() 
missing_values_column = df['Cuisines'].isna().sum() 
missing_values_column = df['Average Cost for two'].isna().sum()

In [20]:
df_cleaned = df.dropna() 
df_cleaned = df.dropna(subset=['Restaurant Name']) 
df_cleaned = df.dropna(subset=['Cuisines']) 
df_cleaned = df.dropna(subset=['Average Cost for two'])

In [22]:
df.describe(include="all")

Restaurant Name      Cuisines  Average Cost for two
count              9542          9542           9542.000000
unique             7437          1825                   NaN
top     Cafe Coffee Day  North Indian                   NaN
freq                 83           936                   NaN
mean                NaN           NaN           1200.326137
std                 NaN           NaN          16128.743876
min                 NaN           NaN              0.000000
25%                 NaN           NaN            250.000000
50%                 NaN           NaN            400.000000
75%                 NaN           NaN            700.000000
max                 NaN           NaN         800000.000000

In [24]:
from sklearn.preprocessing import LabelEncoder 

label_encoder = LabelEncoder() 
df['Restaurant Name'] = label_encoder.fit_transform(df['Restaurant Name']) 
df['Cuisines'] = label_encoder.fit_transform(df['Cuisines'])

In [26]:
df

Restaurant Name  Cuisines  Average Cost for two
0                3743       920                  1100
1                3168      1111                  1200
2                2894      1671                  4000
3                4701      1126                  1500
4                5516      1122                  1500
...               ...       ...                   ...
9546             4437      1813                    80
9547             1312      1824                   105
9548             3065      1110                   170
9549              101      1657                   120
9550             7232       331                    55

[9542 rows x 3 columns]

### Building a Random Forest Model

In [29]:
X = df[['Restaurant Name', 'Average Cost for two']] 
Y = df['Cuisines']

In [31]:
from sklearn.preprocessing import StandardScaler

scaler= StandardScaler()

scaler.fit(X)
X= scaler.transform(X)

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2,random_state=10)  

In [35]:
from sklearn.tree import DecisionTreeClassifier
model_DT = DecisionTreeClassifier(random_state=10,
                                   criterion="gini")
model_DT.fit(X_train,Y_train)
Y_pred = model_DT.predict(X_test) 
print(list(zip(Y_test,Y_pred)))

[(1348, 1348), (1329, 1611), (1608, 1235), (1650, 1655), (1306, 1749), (1514, 549), (168, 50), (331, 1086), (1723, 1723), (582, 663), (682, 682), (1306, 1329), (159, 1098), (201, 1306), (1306, 1306), (58, 58), (1520, 546), (1597, 1381), (774, 766), (518, 497), (1626, 1626), (1306, 1714), (1749, 331), (1520, 1529), (546, 497), (1514, 1306), (1334, 1670), (1212, 518), (958, 1444), (986, 986), (1306, 1626), (1256, 177), (177, 841), (58, 58), (1626, 1626), (1288, 1650), (1514, 1514), (12, 1813), (497, 497), (1306, 1444), (233, 1792), (1554, 1765), (828, 331), (1559, 1598), (230, 230), (1306, 828), (1514, 549), (199, 1444), (1275, 249), (1520, 677), (937, 809), (331, 331), (576, 1340), (1329, 835), (955, 331), (1325, 865), (1306, 1334), (1014, 1691), (518, 583), (177, 1065), (1306, 1306), (1547, 549), (1384, 331), (986, 828), (1618, 280), (1429, 475), (841, 489), (243, 251), (1306, 1329), (1323, 1323), (1699, 1699), (497, 435), (1789, 1789), (1130, 82), (828, 518), (828, 828), (1329, 837), 

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print("Classification report: ") 
print(classification_report(Y_test,Y_pred)) 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification report: 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         1
           6       0.25      0.14      0.18         7
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         1
          13       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         1
          16       1.00      1.00      1.00         2
          18       0.00      0.00      0.00         1
          20       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         2
          24       0.00      0.00      0.00  

### Building Logistic Regression

In [43]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(multi_class="multinomial")
classifier.fit(X_train,Y_train)     
Y_pred = classifier.predict(X_test)
print(Y_pred)

[1306 1306 1306 ... 1306 1306 1306]


In [44]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,Y_pred))
 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification report: 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         7
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         1
          13       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         1
          16       0.00      0.00      0.00         2
          18       0.00      0.00      0.00         1
          20       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         2
          26       0.00      0.00      0.00  

### Conclusion